include:
  - template: Terraform/Base.gitlab-ci.yml

stages:
  - validate
  - build
  - deploy
  - cleanup

variables:
  TF_STATE_NAME: dev-tf-state
  TF_CACHE_KEY: dev-tf-cache
  TF_ROOT: terraform

validate:
  extends: .terraform:validate

build:
  extends: .terraform:build
  script:
    - cd "${TF_ROOT}"
    - gitlab-terraform plan
      -var "s3_name=${S3_NAME}"
    - gitlab-terraform plan-json

deploy:
  extends: .terraform:deploy
  environment:
    name: $TF_STATE_NAME
    on_stop: destroy
  dependencies:
    - build
  rules:
    - when: always

destroy:
  extends: .terraform:destroy
  environment:
    name: $TF_STATE_NAME
    action: stop
  script:
    - cd "${TF_ROOT}"
    - gitlab-terraform destroy
      -var "s3_name=${S3_NAME}"