stages:
  - validate
  - build
  - deploy
  - cleanup

build:
  image: node:21.7.0
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main

validate:
  image:
    name: hashicorp/terraform:1.5.6
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: validate
  script:
    - cd terraform
    - terraform init
    - terraform validate

deploy:
  image: hashicorp/terraform:1.5.6
  stage: deploy
  script:
    - cd "${TF_ROOT}"
    - terraform init
    - terraform apply -auto-approve -var "s3_name=${S3_NAME}"
    - apk add --no-cache python3 py3-pip
    - pip install awscli
    - aws s3 sync dist/ s3://$S3_NAME --delete --region $REGION
  environment:
    name: production
  dependencies:
    - build

destroy:
  image: hashicorp/terraform:1.5.6
  stage: cleanup
  script:
    - cd terraform
    - terraform destroy -auto-approve -var "s3_name=${S3_NAME}"
  when: manual
